apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sofz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0022-tenant/ci10t-786-0022-app/devfile-sample-sofz@sha256:0760543b11041751c66f13572435757ac84daaefa2f5ea43f4b682ce09166924
        name: my-nodejs
        resources: {}
status: {}
