apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sofz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sofz
    app.kubernetes.io/part-of: ci10t-786-0022-app
  name: devfile-sample-sofz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sofz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sofz
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0022-tenant/ci10t-786-0022-app/devfile-sample-sofz@sha256:0760543b11041751c66f13572435757ac84daaefa2f5ea43f4b682ce09166924
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
